symbols = ['AFFLE', 'TEXINFRA', 'DOLPHIN', 'DVL', 'SYRMA', 'MOLDTECH', 'SAHYADRI', 'MUFIN', 'ZEEL', 'DATAMATICS',
           'HILTON', 'SALONA', 'ZODIACLOTH', 'LGHL', 'SMLT', 'CONCORDBIO', 'RBZJEWEL', 'TIL', 'LXCHEM', 'POLYPLEX',
           'VISAKAIND', 'EMMBI', 'MTARTECH', 'ALICON', 'BBOX', 'INNOVACAP', 'KIMS', 'NUVAMA', 'JYOTICNC', 'STOVEKRAFT',
           'BALAMINES', 'GOLDIAM', 'VINATIORGA', 'PARKHOTELS', 'SUKHJITS', 'UNIENTER', 'SASTASUNDR', 'LORDSCHLO',
           'GOCLCORP', 'GPTHEALTH', 'CAPITALSFB', 'MAXESTATES', 'PPAP', '3MINDIA', 'BANSWRAS', 'OAL', 'GRMOVER',
           'SHANKARA', 'SHAREINDIA', 'DTIL', 'KOTHARIPRO', 'WSTCSTPAPR', 'VIPIND', 'CANTABIL', 'DIACABS', 'ORIENTBELL',
           'MASTEK', 'AZAD', 'JSFB', 'TOUCHWOOD', 'CEATLTD', 'PATANJALI', 'BSL', 'FLAIR', 'SAKAR', 'APOLLOPIPE',
           'PRSMJOHNSN', 'SIGNPOST', 'CYBERTECH', 'SKMEGGPROD', 'JINDALPOLY', 'FOODSIN', 'SHREEPUSHK', 'TEMBO',
           'MEGASTAR', 'DELPHIFX', 'VENUSREM', 'BUTTERFLY', 'KANPRPLA', 'BHARATGEAR', 'PRIVISCL', 'SANDUMA',
           'HITECHCORP', 'MASFIN', 'RUPA', 'VERANDA', 'HONASA', 'BLUEJET', 'MANGALAM', 'IITL', 'IRMENERGY', 'CINELINE',
           'SREEL', 'RATNAVEER', 'SHALPAINTS', 'KANORICHEM', 'TATVA', 'BATAINDIA', 'ZFCVINDIA', 'MANAKSIA', 'AGI',
           'CHEMCON', 'JIOFIN', 'JSWINFRA', 'ZUARI', 'BARBEQUE', 'LYKALABS', 'SPANDANA', 'SIGNATURE', 'IVP',
           'UTTAMSUGAR', 'SSWL', 'GOCOLORS', 'GANESHBE', 'CSBBANK', 'OPTIEMUS', 'TBZ', 'MEDICAMEQ', 'DIAMINESQ',
           'NIFTYMEDIA', 'RUBYMILLS', 'GAEL', 'ORBTEXP', 'SINCLAIR', 'VAIBHAVGBL', 'MVGJL', 'HONDAPOWER', 'INDIACEM',
           'SPARC', 'DICIND', 'PODDARMENT', 'APTUS', 'MOTISONS', 'APCL', 'SAKSOFT', 'ALKYLAMINE', 'OCCL', 'GROBTEA',
           'INDIASHLTR', 'SAMHI', 'MUFTI', 'INDIAGLYCO', 'NELCO', 'NIPPOBATRY', 'LOVABLE', 'DELTACORP', 'MARATHON',
           'RAJRATAN', 'NEXT50', 'VALIANTLAB', 'BANDHANBNK', 'KRITI', 'AEROFLEX', 'ENTERO', 'HLEGLAS', 'GICHSGFIN',
           'SIYSIL', 'VENKEYS', 'GREENPANEL', 'MEDPLUS', 'EPL', 'BAYERCROP', 'MANORG', 'RGL', 'INOXINDIA', 'NDTV',
           'SUNTECK', 'BLISSGVS', 'DENORA', 'NUVOCO', 'CREDITACC', 'PRITI', 'GSLSU', 'ADANIENSOL', 'SICALLOG',
           'MOREALTY', 'NCLIND', 'KRYSTAL', 'PFOCUS', 'HIMATSEIDE', 'TARSONS', 'EIFFL', 'BAJAJELEC', 'KTKBANK',
           'SCHAND', 'BANKA', 'SURAJEST', 'JAGSNPHARM', 'MUTHOOTMF', 'EQUAL50ADD', 'EPACK', 'VALIANTORG', 'UDS',
           'VINYLINDIA', 'GSPL', 'KKCL', 'ROUTE', 'HINDWAREAP', 'PYRAMID', 'ZAGGLE', 'HATSUN', 'SESHAPAPER', 'LANDMARK',
           'FUSION', 'CERA', 'IREDA', 'TOTAL', 'RUCHIRA', 'UNIVPHOTO', 'TANLA', 'SRHHYPOLTD', 'ISFT', 'DABUR', 'PGHL',
           'IGL', 'RAMKY', 'JAYBARMARU', 'HERANBA', 'NATHBIOGEN', 'STYLAMIND', 'KNRCON', 'TMB', 'IKIO', 'SAURASHCEM',
           'AVADHSUGAR', 'SULA', 'JTLIND', 'UFLEX', 'PANACEABIO', 'PAYTM', 'GANDHAR', 'SOUTHWEST', 'ANDHRAPAP', 'REFEX',
           'ALKALI', 'HEALTHADD', 'HIL', 'ICRA', 'ARMANFIN', 'MIDQ50ADD', 'MAKEINDIA', 'SBCL', 'FOCUS', 'PONNIERODE',
           'TVSELECT', 'IFBAGRO', 'DEVIT', 'PAGEIND', 'BSOFT', 'PGHH', 'RAMCOCEM', 'KAMOPAINTS', 'YATHARTH',
           'HEXATRADEX', 'RELINFRA', 'NAZARA', 'BIRLACABLE', 'JKPAPER', 'IOLCP', 'JINDWORLD', 'TVSSCS', 'TATATECH',
           'KRBL', 'BERGEPAINT', 'TRIGYN', 'GLOBUSSPR', 'MPHASIS', 'STLTECH', 'NAVINIFTY', 'IIFL', 'BSHSL', 'NAHARCAP',
           'WHEELS', 'HEALTHIETF', 'APCOTEXIND', 'KANSAINER', 'UNIPARTS', 'AMBIKCO', 'DALMIASUG', 'ASHAPURMIN',
           'SHARDACROP', 'DIAMONDYD', 'INDOCO', 'LOWVOL', 'HEUBACHIND', 'DBOL', 'JUNIPER', 'AWL', 'HCLTECH',
           'LICMFGOLD', 'IDEAFORGE', 'VISHNU', 'INDUSINDBK', 'RUSHIL', 'NIFTY50ADD', 'MUKANDLTD', 'ACLGATI', 'APTECHT',
           'KABRAEXTRU', 'VSTL', 'COFORGE', 'GREAVESCOT', 'IBULHSGFIN', 'DREAMFOLKS', 'NIFTYETF', 'RISHABH', 'SFL',
           'AXISTECETF', 'ANGELONE', 'HGS', 'SOMANYCERA', 'M&MFIN', 'RELCHEMQ', 'EMSLIMITED', 'DAVANGERE', 'KALAMANDIR',
           'BORORENEW', 'RKSWAMY', 'PLATIND', 'CHEVIOT', 'TCIEXP', 'DALBHARAT', 'JGCHEM', 'CHEMPLASTS', 'HINDUNILVR',
           'BANKETF', 'ASIANPAINT', 'CYIENT', 'AGARIND', 'SATIA', 'RRKABEL', 'CRAFTSMAN', 'HIKAL', 'LTTS', 'HNDFDS',
           'BALUFORGE', 'LAMBODHARA', 'AVALON', 'MHLXMIRU', 'NIITLTD', 'GNA', 'PEL', 'KRSNAA', 'GHCL', 'BAJAJFINSV',
           'CCL', 'RSYSTEMS', 'SONATSOFTW', 'SPORTKING', 'PRECAM', 'ACI', 'BAJFINANCE', 'HDFCBANK', 'IPL', 'AKZOINDIA',
           'SIS', 'AMNPLST', 'BOROLTD', 'SBIETFIT', 'KITEX', 'ESABINDIA', 'ATFL', 'KERNEX', 'SIGMA', 'ASKAUTOLTD',
           'GSEC10IETF', 'MEDIASSIST', 'SONACOMS', 'EMAMIPAP', 'ORIENTELEC', 'PIIND', 'STARHEALTH', 'HOMEFIRST', 'ITC',
           'NIFTYBETF', 'CANFINHOME', 'NAVINFLUOR', 'NIFMID150', 'KAJARIACER', 'RPSGVENT', 'PVRINOX', 'YATRA', 'GLOBAL',
           'TITAN', 'DEVYANI', 'FEDFINA', 'LIQUIDETF', 'HDFCLIQUID', 'LIQUIDCASE', 'INFOBEAN', 'SBICARD', 'SYNGENE',
           'YASHO', 'SENSEXIETF', 'AUBANK', 'LIQUID1', 'RAJESHEXPO', 'FLUOROCHEM', 'LIQUIDADD', 'ADANIENT', 'EXICOM',
           'LIQUIDSBI', 'IDFC', 'KOTAKBANK', 'INSECTICID', 'LIQUID', 'UPL', 'LIQUIDIETF', 'LIQUIDBEES', 'PUNJABCHEM',
           'CELLO', 'ATGL', 'PVSL', 'SRM', 'TIPSFILMS', 'AETHER', 'MOLDTKPAC', 'SHREECEM', 'NIFITETF', 'DYNPRO', 'LINC',
           'EXPLEOSOL', 'INFY', 'JLHL', 'BLSE', 'NILKAMAL', 'HDFCLIFE', 'HAPPSTMNDS', 'BANARISUG', 'NAHARSPING', 'GSS',
           'INDIAMART', 'RAIN', 'RIIL', 'BALPHARMA', 'SRF', 'ADORWELD', 'LOYALTEX', 'DOMS', 'DEEPAKFERT', 'CENTURYPLY',
           'SPECIALITY', 'SHEMAROO', 'RAMAPHO', 'DPWIRES', 'SUPERHOUSE', 'HEIDELBERG', 'RHIM', 'DHAMPURSUG', 'BBTCL',
           'JUBLFOOD', 'LTIM', 'BHARATWIRE', 'KAKATCEM', 'TTKPRESTIG', 'ICEMAKE', 'NIITMTS', 'JKLAKSHMI', 'ASTERDM',
           'DHARMAJ', 'RELAXO', 'TOKYOPLAST', 'SUNCLAY', 'MAYURUNIQ', 'NAHARINDUS', 'JAYSREETEA', 'BAJAJHCARE',
           'PERSISTENT', 'GNFC', 'GOPAL', 'RPTECH', 'MAHAPEXLTD', 'TVSHLTD', 'AKSHARCHEM', 'SAPPHIRE', 'VPRPL',
           'BHAGERIA', 'PSPPROJECT', 'CLEAN', 'LAOPALA', 'MENONBE', 'ATUL', 'RSWM', 'UCAL', 'APOLSINHOT', 'HAPPYFORGE',
           'GULPOLY', 'BHARTIHEXA', 'GMMPFAUDLR', 'PDSL', 'NURECA', 'COASTCORP', 'AARTIDRUGS', 'EVEREADY', 'UNIDT',
           'XPROINDIA', 'ROSSARI', 'TATAELXSI', 'VRLLOG', 'GARFIBRES', 'INDIGOPNTS', 'CAMPUS', 'ANURAS', 'JOCIL',
           'SAGCEM', 'BALRAMCHIN', 'DIVGIITTS', 'DONEAR', 'SHREYAS', 'SANGAMIND', 'ONWARDTEC', 'KRISHANA', 'RBA',
           'FINOPB', 'SUMICHEM', 'PODDARHOUS', 'APEX', 'COSMOFIRST', 'ANDHRSUGAR', 'CONSOFINVT', 'MANGCHEFER',
           'JNKINDIA', 'METROBRAND', 'KUANTUM', 'KINGFA', 'BAJEL', 'REDTAPE', 'MUTHOOTCAP', 'PALREDTEC', 'NETWEB',
           'SHIVALIK', 'NAHARPOLY', 'AHLEAST', 'ASTEC', 'AUTOAXLES', 'LTFOODS', 'MANYAVAR', 'MONTECARLO', 'AIIL',
           'FINEORG', 'MBAPL', 'GALAXYSURF', 'SIRCA', 'MATRIMONY', 'POKARNA', 'AVROIND', 'REPL', 'SUNDRMFAST',
           'HARIOMPIPE',
           'TASTYBITE', 'KIRIINDUS', 'SRGHFL', 'SEMAC', 'GLOSTERLTD', 'SECMARK', 'ROLEXRINGS', 'ASIANHOTNR',
           'PRINCEPIPE']

s = ['WIPRO', 'GRASIM', 'ULTRACEMCO', 'TVSMOTOR', 'EICHERMOT', 'VOLTAS', 'APOLLOHOSP', 'INFY', 'SHREECEM', 'HDFCAMC', 'M&M', 'CHOLAFIN', 'BHARTIARTL', 'SBILIFE', 'HDFCLIFE', 'KEI', 'GODREJPROP', 'ESCORTS', 'JSWSTEEL', 'SOLARINDS', 'POLYCAB', 'BRITANNIA', 'RECLTD', 'GLENMARK', 'LTIM', 'DALBHARAT', 'LUPIN', 'SUPREMEIND', 'TECHM', 'PFC', 'SUNPHARMA', 'TCS', 'ICICIBANK', 'TITAN', 'INDHOTEL', 'HCLTECH', 'ITC', 'LT', 'CUMMINSIND', 'SHRIRAMFIN', 'ASTRAL', 'CHAMBLFERT', 'UNITDSPR', 'OIL', 'VEDL', 'NYKAA', 'JINDALSTEL', 'MUTHOOTFIN', 'MPHASIS', 'BPCL', 'KOTAKBANK', 'APOLLOTYRE', 'BAJFINANCE', 'TATAELXSI', 'BHARATFORG', 'ICICIPRULI', 'POWERGRID', 'BEL', 'DRREDDY', 'TATACONSUM', 'MARUTI', 'CIPLA', 'PAGEIND', 'NATIONALUM', 'MGL', 'GAIL', 'ABB', 'NTPC', 'BOSCHLTD', 'SYNGENE', 'JKCEMENT', 'OBEROIRLTY', 'IEX', 'TORNTPHARM', 'NMDC', 'AUROPHARMA', 'SAIL', 'LTTS', 'BHEL', 'GMRAIRPORT', 'ADANIGREEN', 'HAL', 'PIDILITIND', 'IOC', 'SIEMENS', 'MFSL', 'CDSL', 'HEROMOTOCO', 'BANDHANBNK', 'RAMCOCEM', 'MRF', 'CROMPTON', 'PEL', 'DLF', 'SBIN', 'TIINDIA', 'MOTHERSON', 'DELHIVERY', 'CESC', 'PRESTIGE', 'NESTLEIND', 'BERGEPAINT', 'BANKBARODA', 'HINDALCO', 'NCC', 'SRF', 'ADANIENSOL', 'LODHA', 'CGPOWER', 'HINDPETRO', 'LAURUSLABS', 'PNB', 'COFORGE', 'DIVISLAB', 'SBICARD', 'LTF', 'HDFCBANK', 'BAJAJ-AUTO', 'IRCTC', 'HINDUNILVR', 'ICICIGI', 'HFCL', 'TATASTEEL', 'GODREJCP', 'NAUKRI', 'BALKRISIND', 'HAVELLS', 'PAYTM', 'DABUR', 'MARICO', 'JSL', 'CAMS', 'M&MFIN', 'TRENT', 'DMART', 'NHPC', 'BANKINDIA', 'ONGC', 'AXISBANK', 'TATAMOTORS', 'TATACOMM', 'TATACHEM', 'IDFCFIRSTB', 'ABCAPITAL', 'ZYDUSLIFE', 'NBCC', 'ASHOKLEY', 'GRANULES', 'ALKEM', 'AMBUJACEM', 'PIIND', 'BSOFT', 'FEDERALBNK', 'INDIANB', 'BAJAJFINSV', 'TORNTPOWER', 'EXIDEIND', 'ASIANPAINT', 'CANBK', 'AUBANK', 'LICHSGFIN', 'TATAPOWER', 'ACC', 'PHOENIXLTD', 'JSWENERGY', 'INDUSTOWER', 'OFSS', 'CONCOR', 'ADANIPORTS', 'AARTIIND', 'MAXHEALTH', 'DEEPAKNTR', 'HUDCO', 'HINDCOPPER', 'UPL', 'LICI', 'POLICYBZR', 'IGL', 'SJVN', 'ABFRL', 'BIOCON', 'PETRONET', 'SONACOMS', 'COLPAL', 'RBLBANK', 'MANAPPURAM', 'CYIENT', 'YESBANK', 'INDUSINDBK', 'IRFC', 'KPITTECH', 'TITAGARH', 'UNIONBANK', 'IDEA', 'KALYANKJIL', 'PERSISTENT', 'ADANIENT', 'RELIANCE', 'ATGL', 'APLAPOLLO', 'JIOFIN', 'COALINDIA', 'MCX', 'BSE', 'PATANJALI', 'IRB', 'VBL', 'JUBLFOOD', 'POONAWALLA', 'DIXON', 'INDIGO', 'TATATECH', 'IIFL', 'IREDA', 'ANGELONE']

symbol200 = ['BDL',
             'CUMMINSIND',
             'ZEEL',
             'LICI',
             'TRENT',
             'OIL',
             'MANKIND',
             'HAL',
             'MAXHEALTH',
             'TORNTPOWER',
             'PIIND',
             'TATACOMM',
             'TATAPOWER',
             'MFSL',
             'SBIN',
             'BANKBARODA',
             'ALKEM',
             'IOC',
             'BPCL',
             'BANKINDIA',
             'CANBK',
             'KPITTECH',
             'JSWENERGY',
             'POWERGRID',
             'CONCOR',
             'VOLTAS',
             'OBEROIRLTY',
             'VBL',
             'UNIONBANK',
             'MSUMI',
             'BEL',
             'NAUKRI',
             'COALINDIA',
             'PAGEIND',
             'PATANJALI',
             'HINDALCO',
             'ZYDUSLIFE',
             'INDIANB',
             'MAZDOCK',
             'TCS',
             'HCLTECH',
             'RELIANCE',
             'LUPIN',
             'AUROPHARMA',
             'INDUSTOWER',
             'BAJAJ-AUTO',
             'GAIL',
             'APOLLOHOSP',
             'ONGC',
             'LICHSGFIN',
             'BOSCHLTD',
             'ACC',
             'BAJAJHLDNG',
             'MPHASIS',
             'YESBANK',
             'HINDPETRO',
             'DLF',
             'BHARTIARTL',
             'PNB',
             'NTPC',
             'NMDC',
             'HEROMOTOCO',
             'INDIGO',
             'DMART',
             'COFORGE',
             'INDHOTEL',
             'ESCORTS',
             'ABCAPITAL',
             'SRF',
             'SUNPHARMA',
             'RECLTD',
             'LTTS',
             'DRREDDY',
             'MRF',
             'SUNTV',
             'RVNL',
             'BHARATFORG',
             'SBICARD',
             'HDFCAMC',
             'INFY',
             'APLAPOLLO',
             'POLICYBZR',
             'HAVELLS',
             'BHEL',
             'TORNTPHARM',
             'CROMPTON',
             'ICICIGI',
             'JUBLFOOD',
             'GUJGASLTD',
             'IRFC',
             'MCDOWELL-N',
             'JINDALSTEL',
             'NHPC',
             'PFC',
             'BATAINDIA',
             'TATASTEEL',
             'HINDUNILVR',
             'LTIM',
             'NAVINFLUOR',
             'COROMANDEL',
             'PERSISTENT',
             'ASTRAL',
             'TITAN',
             'TECHM',
             'IPCALAB',
             'ADANIPORTS',
             'DABUR',
             'LAURUSLABS',
             'BANDHANBNK',
             'MARICO',
             'TATAELXSI',
             'IRCTC',
             'SIEMENS',
             'SBILIFE',
             'PGHH',
             'PRESTIGE',
             'TATAMOTORS',
             'DIXON',
             'FACT',
             'IDEA',
             'ADANIPOWER',
             'CIPLA',
             'ASHOKLEY',
             'TATAMTRDVR',
             'DEEPAKNTR',
             'AMBUJACEM',
             'LT',
             'TVSMOTOR',
             'DEVYANI',
             'ABFRL',
             'DIVISLAB',
             'VEDL',
             'BAJAJFINSV',
             'POONAWALLA',
             'BERGEPAINT',
             'WIPRO',
             'UBL',
             'POLYCAB',
             'FEDERALBNK',
             'L&TFH',
             'BIOCON',
             'BALKRISIND',
             'ATGL',
             'TATACHEM',
             'M&MFIN',
             'PETRONET',
             'CGPOWER',
             'ADANIENT',
             'HDFCBANK',
             'ASIANPAINT',
             'GODREJCP',
             'AWL',
             'M&M',
             'MARUTI',
             'JSWSTEEL',
             'ADANIENSOL',
             'ICICIPRULI',
             'COLPAL',
             'APOLLOTYRE',
             'BAJFINANCE',
             'FORTIS',
             'DELHIVERY',
             'MOTHERSON',
             'RAMCOCEM',
             'ADANIGREEN',
             'IGL',
             'GRASIM',
             'ULTRACEMCO',
             'GLAND',
             'SYNGENE',
             'INDUSINDBK',
             'TATACONSUM',
             'SHREECEM',
             'HDFCLIFE',
             'SHRIRAMFIN',
             'CHOLAFIN',
             'PIDILITIND',
             'IDFCFIRSTB',
             'ITC',
             'DALBHARAT',
             'LODHA',
             'ABB',
             'UPL',
             'TIINDIA',
             'SONACOMS',
             'SAIL',
             'NYKAA',
             'ICICIBANK',
             'EICHERMOT',
             'NESTLEIND',
             'AXISBANK',
             'FLUOROCHEM',
             'BRITANNIA',
             'GODREJPROP',
             'LALPATHLAB',
             'AUBANK',
             'KOTAKBANK',
             'PEL',
             'MUTHOOTFIN',
             'PAYTM']
small = ['NATIONALUM',	'CROMPTON',	'AEGISLOG',	'SAMMAANCAP',	'AVANTIFEED',	'BRIGADE',	'DEEPAKFERT',	'TECHNOE',	'KNRCON',	'CAPLIPOINT',	'JINDALSAW',	'RAJESHEXPO',	'BBTC',	'EQUITASBNK',	'RKFORGE',	'IFCI',	'QUESS',	'ACI',	'AMBER',	'ANANDRATHI',	'MASTEK',	'SWANENERGY',	'PRAJIND',	'GPIL',	'SHYAMMETL',	'PTCIL',	'CDSL',	'HEG',	'TRITURBINE',	'HFCL',	'CERA',	'NBCC',	'ALOKINDS',	'KANSAINER',	'KEC',	'GNFC',	'JUBLINGREA',	'TVSSCS',	'GRINFRA',	'DOMS',	'NSLNISP',	'GPPL',	'TBOTEK',	'ABSLAMC',	'LALPATHLAB',	'KFINTECH',	'EIHOTEL',	'ASTERDM',	'JBCHEPHARM',	'FSL',	'NETWEB',	'NETWORK18',	'KAYNES',	'JBMA',	'CLEAN',	'MAHSEAMLES',	'RRKABEL',	'CANFINHOME',	'CCL',	'UCOBANK',	'J&KBANK',	'BIRLACORPN',	'KPIL',	'HINDCOPPER',	'WELSPUNLIV',	'CRAFTSMAN',	'WELCORP',	'CASTROLIND',	'HSCL',	'JKTYRE',	'ZEEL',	'SBFC',	'GLENMARK',	'NATCOPHARM',	'LATENTVIEW',	'HBLPOWER',	'SCI',	'SOBHA',	'SONATSOFTW',	'ACE',	'CHEMPLASTS',	'360ONE',	'IEX',	'BLUESTARCO',	'KIRLOSENG',	'ISEC',	'CESC',	'TRIDENT',	'DATAPATTNS',	'TTML',	'CHAMBLFERT',	'INDGN',	'FINPIPE',	'CENTRALBK',	'ENGINERSIN',	'UJJIVANSFB',	'FINEORG',	'RBLBANK',	'MMTC',	'HOMEFIRST',	'REDINGTON',	'JKLAKSHMI',	'VIPIND',	'CEATLTD',	'OLECTRA',	'KARURVYSYA',	'IRCON',	'ERIS',	'SIGNATURE',	'TEJASNET',	'NH',	'JUSTDIAL',	'VINATIORGA',	'SUMICHEM',	'INDIACEM',	'RITES',	'ATUL',	'BATAINDIA',	'INDIAMART',	'METROPOLIS',	'VTL',	'NUVOCO',	'MAHLIFE',	'MANAPPURAM',	'GILLETTE',	'AAVAS',	'CUB',	'SUVENPHAR',	'JWL',	'CHALET',	'GODREJAGRO',	'GRAPHITE',	'GMDCLTD',	'LAURUSLABS',	'TITAGARH',	'PFIZER',	'SPARC',	'PVRINOX',	'ALKYLAMINE',	'RAMCOCEM',	'INTELLECT',	'PCBL',	'NAVINFLUOR',	'WHIRLPOOL',	'JMFINANCIL',	'APTUS',	'CGCL',	'ANGELONE',	'GAEL',	'CENTURYPLY',	'GRANULES',	'AARTIIND',	'JYOTICNC',	'IIFL',	'SYRMA',	'RHIM',	'INOXWIND',	'MOTILALOFS',	'INOXINDIA',	'KIMS',	'BIKAJI',	'MCX',	'RTNINDIA',	'NUVAMA',	'CREDITACC',	'GVT&D',	'GRSE',	'WESTLIFE',	'GODFRYPHLP',	'USHAMART',	'FINCABLES',	'LEMONTREE',	'MANYAVAR',	'NCC',	'RAILTEL',	'JUBLPHARMA',	'FIVESTAR',	'DEVYANI',	'GSFC',	'MAPMYINDIA',	'RCF',	'CHENNPETRO',	'BLS',	'SAPPHIRE',	'ABREL',	'JPPOWER',	'VGUARD',	'AFFLE',	'SANOFI',	'APLLTD',	'CAMPUS',	'CYIENT',	'ZENSARTECH',	'RATNAMANI',	'RENUKA',	'HAPPSTMNDS',	'POLYMED',	'VARROC',	'CAMS',	'MINDACORP',	'BSOFT',	'PNCINFRA',	'KSB',	'VIJAYA',	'TRIVENI',	'KAJARIACER',	'APARINDS',	'SWSOLAR',	'ARE&M',	'ANANTRAJ',	'EMCURE',	'EASEMYTRIP',	'RADICO',	'CIEINDIA',	'KIRLOSBROS',	'SCHNEIDER',	'PEL',	'CELLO',	'ROUTE',	'JYOTHYLAB',	'BALAMINES',	'CONCORDBIO',	'TANLA',	'SAREGAMA',	'ASAHIINDIA',	'RAYMOND',	'ELGIEQUIP',	'BEML',	'EIDPARRY',	'AADHARHFC',	'ITI',	'ELECON',	'DBREALTY',	'UTIAMC',	'GESHIP',	'BLUEDART',	'BALRAMCHIN',	'ECLERX',	'PNBHOUSING',	'RAINBOW',	'ASTRAZEN',	'CHOLAHLDNG',	'PPLPHARMA',	'GODIGIT',	'AKUMS',	'GSPL',	'BASF',	'NEWGEN',	'MGL',	'HONASA'
]
n = ['GODREJPROP','POWERGRID']
import pandas as pd
from curl_cffi import requests
from io import StringIO

# Define the URL and parameters
url = "https://www.nseindia.com/api/equity-stockIndices"
params = {
    "csv": "true",
    "index": "SECURITIES IN F&O",  # Corrected index name
    "selectValFormat": "crores"
}

# Set headers to mimic a browser request
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "*/*",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www.nseindia.com/",
    "DNT": "1",
}

def get_stock_list():
    try:
        with requests.Session() as s:
            # Set headers
            s.headers.update(headers)
            
            # First request to get cookies (impersonate Chrome)
            s.get("https://www.nseindia.com/", impersonate="chrome110")
            
            # Make the API request
            response = s.get(
                url,
                params=params,
                impersonate="chrome110"
            )
            
            if response.status_code == 200:
                # Read CSV data into pandas DataFrame
                csv_data = StringIO(response.text)
                df = pd.read_csv(csv_data)
                return df
            else:
                print(f"Request failed with status code: {response.status_code}")
                return None
                
    except Exception as e:
        print(f"An error occurred: {str(e)}")
        return None

if __name__ == "__main__":
    stock_df = get_stock_list()
    if stock_df is not None:
        print("Successfully fetched stock list:")
        v = stock_df['SYMBOL \n'].to_list()
        print(v)